GET http://localhost:8084/ld/add

###
GET http://localhost:8084/lds

###
GET http://localhost:8084/users

###
GET http://localhost:8084/add

###
GET http://localhost:8084/users/13

###
GET http://localhost:8084/users/query?name=zhangsan
