spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: 192.168.226.128
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nogodfyb/config-repo.git
          force-pull: true
          # 强制拉取资源文件
          # search-paths:
          username: nogodfyb
          password: fyb1994123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

server:
  port: 60002


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
