###
POST http://localhost:8080/login1


###  测试token拦截器
POST http://localhost:8080/api/getUser
headerUserId:userId---xxx
headerUserToken:68f20f86-796d-493c-9fea-04710a5eb3a9

###
GET  http://localhost:8080/sso/login
